// src/pages/Home.tsx
import React, { useState } from 'react';
import { Slider } from 'antd';
import { DeleteOutlined } from '@ant-design/icons';
import { v4 as uuidv4 } from 'uuid';
import ProcessNodeDestination from '../components/ProcessNodeDestination';
import ProcessNodeScale from '../components/ProcessNodeScale';
import ProcessNodeSource from '../components/ProcessNodeSource';
import ProcessNodeCompress from '../components/ProcessNodeCompress';
import { EnumImageType, EnumScaleType, ImageInfo } from '../types/image';
import { getImageDimensions } from '../utils';
import { compressAndScaleImage } from '../utils/process';
import './Home.css';
import { getImageType } from '../utils/image';

const Home: React.FC = () => {
  const [sourceKey, setSourceKey] = useState<number>(0);
  const [originalImages, setOriginalImages] = useState<ImageInfo[]>([]);
  const [processedImages, setProcessedImages] = useState<ImageInfo[]>([]);
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState<number>(0);

  const [quality, setQuality] = useState<number>(100);
  const [imageType, setImageType] = useState<EnumImageType>(EnumImageType.SAME);

  const [scaleType, setScaleType] = useState<EnumScaleType>(EnumScaleType.RATIO);
  const [scaleRatio, setScaleRatio] = useState<number>(1);
  const [scaleWidth, setScaleWidth] = useState<number>(256);

  const [error, setError] = useState<string>('');

  const onImageSuccess = async (files: File[]) => {
    setError('');
    const processedImages: ImageInfo[] = [];

    for (const file of files) {
      const originalUrl = URL.createObjectURL(file);
      const dimensions = await getImageDimensions(originalUrl);
      processedImages.push({
        id: uuidv4(),
        url: originalUrl,
        name: file.name,
        fileSize: file.size,
        type: getImageType(file.type),
        blob: file,
        imageSize: dimensions,
      });
    }
    setOriginalImages(prev => prev.concat(processedImages));
    setProcessedImages([]);
  };

  const onImageError = (err: Error) => {
    setError(err instanceof Error ? err.message : '处理图片时出错');
  };

  const processImages = async () => {
    if (originalImages.length === 0) {
      setError('请选择图片');
      return;
    }

    setProcessing(true);
    try {
      setError('');
      setProgress(0);

      const processedImages: ImageInfo[] = [];

      for (let i = 0; i < originalImages.length; i++) {
        const originalImage = originalImages[i];
        try {
          const result = await compressAndScaleImage(originalImage, {
            type: imageType,
            quality,
            scale: {
              type: scaleType,
              ratio: scaleRatio,
              width: scaleWidth
            },
          });

          processedImages.push({
            id: originalImage.id, // 使用原始图片的 id
            url: result.url,
            name: result.name,
            fileSize: result.blob.size,
            type: result.type,
            blob: result.blob,
            originalSize: result.originalSize,
            imageSize: result.dimensions,
          });
        } catch (error: any) {
          processedImages.push({
            ...originalImage,
            error: error.message,
          });
        }
        // 更新进度
        setProcessedImages(processedImages);
        setProgress(Math.round(((i + 1) / originalImages.length) * 100));
      }

      setProcessedImages(processedImages);
    } catch (error: any) {
      onImageError(error);
    }
    setProcessing(false);
  };

  // 添加删除原始图片的处理函数
  const handleDeleteOriginal = (image: ImageInfo) => {
    URL.revokeObjectURL(image.url);
    setOriginalImages(prev => prev.filter(item => item.id !== image.id));
    // 当删除原始图片时，也需要删除对应的处理后图片
    const processedImage = processedImages.find(item => item.id === image.id);
    if (processedImage) {
      URL.revokeObjectURL(processedImage.url);
    }
    setProcessedImages(prev => prev.filter(item => item.id !== image.id));
    // 更新key以强制重新渲染ProcessNodeSource组件
    setSourceKey(prev => prev + 1);
  };

  // 添加删除处理后图片的处理函数
  const handleDeleteProcessed = (image: ImageInfo) => {
    URL.revokeObjectURL(image.url);
    setProcessedImages(prev => prev.filter(item => item.id !== image.id));
  };

  // 添加清空原始图片列表的处理函数
  const handleClearOriginal = () => {
    originalImages.forEach(image => {
      URL.revokeObjectURL(image.url);
    });
    processedImages.forEach(image => {
      URL.revokeObjectURL(image.url);
    });
    setOriginalImages([]);
    setProcessedImages([]);
    // 更新key以强制重新渲染ProcessNodeSource组件
    setSourceKey(prev => prev + 1);
  };

  // 添加清空处理后图片列表的处理函数
  const handleClearProcessed = () => {
    processedImages.forEach(image => {
      URL.revokeObjectURL(image.url);
    });
    setProcessedImages([]);
  };

  return (
    <div className="image-tool">
      <div className="image-tool__body">
        <div className="image-tool__input">
          <div className="image-tool__preview-title">图片配置</div>
          <ProcessNodeSource key={sourceKey} onChange={onImageSuccess} onError={onImageError} />
          <ProcessNodeCompress
            quality={quality}
            imageType={imageType}
            scaleType={scaleType}
            onChange={(quality, imageType, scaleType) => {
              setQuality(quality);
              setImageType(imageType);
              setScaleType(scaleType)
            }}
          ></ProcessNodeCompress>
          <ProcessNodeScale
            scaleType={scaleType}
            scaleRatio={scaleRatio}
            scaleWidth={scaleWidth}
            onChange={(scale, scaleWidth) => {
              setScaleRatio(scale);
              setScaleWidth(scaleWidth)
            }}
          ></ProcessNodeScale>

          <button
            className="image-tool__button"
            onClick={processImages}
            disabled={originalImages.length === 0 || processing}
          >
            {processing ? '正在处理' : '开始处理'} ({originalImages.length} 张图片)
          </button>
          {originalImages.length > 0 && (
            <>
              <div style={{ marginTop: '16px', padding: '0 10px' }}>
                <Slider value={progress} />
                <div style={{ textAlign: 'center', marginTop: '8px' }}>
                  <div className="image-tool__status">处理进度：{progress}%</div>
                </div>
              </div>
            </>
          )}
          {error && <div className="image-tool__error">{error}</div>}
        </div>
        <div className="image-tool__output">
          {originalImages.length > 0 && (
            <div className="image-tool__preview">
              <div className="image-tool__preview-group">
                <div className="image-tool__preview-head">
                  <div className="image-tool__preview-title">原始图片</div>
                  <DeleteOutlined
                    className="process-node-destination__link"
                    onClick={handleClearOriginal}
                    style={{ fontSize: '16px', cursor: 'pointer' }}
                  />
                </div>
                <div className="image-tool__preview-list">
                  {originalImages.map(image => (
                    <ProcessNodeDestination
                      key={image.id}
                      title={`原始图片 ${originalImages.findIndex(img => img.id === image.id) + 1}`}
                      image={image}
                      onDelete={() => handleDeleteOriginal(image)}
                    />
                  ))}
                </div>
              </div>
              {processedImages.length > 0 && (
                <div className="image-tool__preview-group">
                  <div className="image-tool__preview-head">
                    <div className="image-tool__preview-title">处理后图片</div>
                    <DeleteOutlined
                      className="process-node-destination__link"
                      onClick={handleClearProcessed}
                      style={{ fontSize: '16px', cursor: 'pointer' }}
                    />
                  </div>
                  <div className="image-tool__preview-list">
                    {processedImages.map(image => (
                      <ProcessNodeDestination
                        key={image.id}
                        title={`处理后图片 ${processedImages.findIndex(img => img.id === image.id) + 1}`}
                        image={image}
                        onDelete={() => handleDeleteProcessed(image)}
                      />
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Home;

// src/pages/Home.vue
<template>
  <div class="image-tool">
    <div class="image-tool__body">
      <div class="image-tool__input">
        <div class="image-tool__preview-title">图片配置</div>
        <ProcessNodeSource :key="sourceKey" @change="onImageSuccess" @error="onImageError" />
        <ProcessNodeCompress
          :quality="quality"
          :image-type="imageType"
          :scale-type="scaleType"
          @change="(q: number, t: EnumImageType, s: EnumScaleType) => {
            quality = q;
            imageType = t;
            scaleType = s;
          }"
        ></ProcessNodeCompress>
        <ProcessNodeScale
          :scale-type="scaleType"
          :scale-ratio="scaleRatio"
          :scale-width="scaleWidth"
          @change="(ratio: number, width: number) => {
            scaleRatio = ratio;
            scaleWidth = width;
          }"
        ></ProcessNodeScale>

        <button
          class="image-tool__button"
          @click="processImages"
          :disabled="originalImages.length === 0 || processing"
        >
          {{ processing ? '正在处理' : '开始处理' }} ({{ originalImages.length }} 张图片)
        </button>
        <div v-if="originalImages.length > 0" style="margin-top: 16px; padding: 0 10px">
          <a-slider :value="progress" />
          <div style="text-align: center; margin-top: 8px">
            <div class="image-tool__status">处理进度：{{ progress }}%</div>
          </div>
        </div>
        <div v-if="error" class="image-tool__error">{{ error }}</div>
      </div>
      <div class="image-tool__output">
        <div v-if="originalImages.length > 0" class="image-tool__preview">
          <div class="image-tool__preview-group">
            <div class="image-tool__preview-head">
              <div class="image-tool__preview-title">原始图片</div>
              <DeleteOutlined
                class="process-node-destination__link"
                @click="handleClearOriginal"
                style="font-size: 16px; cursor: pointer"
              />
            </div>
            <div class="image-tool__preview-list">
              <ProcessNodeDestination
                v-for="(image, index) in originalImages"
                :key="image.id"
                :title="`原始图片 ${index + 1}`"
                :image="image"
                @delete="handleDeleteOriginal(image)"
              />
            </div>
          </div>
          <div v-if="processedImages.length > 0" class="image-tool__preview-group">
            <div class="image-tool__preview-head">
              <div class="image-tool__preview-title">处理后图片</div>
              <DeleteOutlined
                class="process-node-destination__link"
                @click="handleClearProcessed"
                style="font-size: 16px; cursor: pointer"
              />
            </div>
            <div class="image-tool__preview-list">
              <ProcessNodeDestination
                v-for="(image, index) in processedImages"
                :key="image.id"
                :title="`处理后图片 ${index + 1}`"
                :image="image"
                @delete="handleDeleteProcessed(image)"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { Slider as ASlider } from 'ant-design-vue';
import { DeleteOutlined } from '@ant-design/icons-vue';
import { v4 as uuidv4 } from 'uuid';
import ProcessNodeDestination from '../components/ProcessNodeDestination.vue';
import ProcessNodeScale from '../components/ProcessNodeScale.vue';
import ProcessNodeSource from '../components/ProcessNodeSource.vue';
import ProcessNodeCompress from '../components/ProcessNodeCompress.vue';
import { EnumImageType, EnumScaleType, ImageInfo } from '../types/image';
import { getImageDimensions } from '../utils';
import { compressAndScaleImage } from '../utils/process';
import { getImageType } from '../utils/image';
import './Home.css';

const sourceKey = ref<number>(0);
const originalImages = ref<ImageInfo[]>([]);
const processedImages = ref<ImageInfo[]>([]);
const processing = ref<boolean>(false);
const progress = ref<number>(0);

const quality = ref<number>(100);
const imageType = ref<EnumImageType>(EnumImageType.SAME);

const scaleType = ref<EnumScaleType>(EnumScaleType.RATIO);
const scaleRatio = ref<number>(1);
const scaleWidth = ref<number>(256);

const error = ref<string>('');

const onImageSuccess = async (files: File[]) => {
  error.value = '';
  const newProcessedImages: ImageInfo[] = [];

  for (const file of files) {
    const originalUrl = URL.createObjectURL(file);
    const dimensions = await getImageDimensions(originalUrl);
    newProcessedImages.push({
      id: uuidv4(),
      url: originalUrl,
      name: file.name,
      fileSize: file.size,
      type: getImageType(file.type),
      blob: file,
      imageSize: dimensions,
    });
  }
  originalImages.value = originalImages.value.concat(newProcessedImages);
  processedImages.value = [];
};

const onImageError = (err: Error) => {
  error.value = err instanceof Error ? err.message : '处理图片时出错';
};

const processImages = async () => {
  if (originalImages.value.length === 0) {
    error.value = '请选择图片';
    return;
  }

  processing.value = true;
  try {
    error.value = '';
    progress.value = 0;

    const newProcessedImages: ImageInfo[] = [];

    for (let i = 0; i < originalImages.value.length; i++) {
      const originalImage = originalImages.value[i];
      try {
        const result = await compressAndScaleImage(originalImage, {
          type: imageType.value,
          quality: quality.value,
          scale: {
            type: scaleType.value,
            ratio: scaleRatio.value,
            width: scaleWidth.value
          },
        });

        newProcessedImages.push({
          id: originalImage.id,
          url: result.url,
          name: result.name,
          fileSize: result.blob.size,
          type: result.type,
          blob: result.blob,
          originalSize: result.originalSize,
          imageSize: result.dimensions,
        });
      } catch (err: any) {
        newProcessedImages.push({
          ...originalImage,
          error: err.message,
        });
      }
      processedImages.value = newProcessedImages;
      progress.value = Math.round(((i + 1) / originalImages.value.length) * 100);
    }

    processedImages.value = newProcessedImages;
  } catch (err: any) {
    onImageError(err);
  }
  processing.value = false;
};

const handleDeleteOriginal = (image: ImageInfo) => {
  URL.revokeObjectURL(image.url);
  originalImages.value = originalImages.value.filter(item => item.id !== image.id);
  const processedImage = processedImages.value.find(item => item.id === image.id);
  if (processedImage) {
    URL.revokeObjectURL(processedImage.url);
  }
  processedImages.value = processedImages.value.filter(item => item.id !== image.id);
  sourceKey.value = sourceKey.value + 1;
};

const handleDeleteProcessed = (image: ImageInfo) => {
  URL.revokeObjectURL(image.url);
  processedImages.value = processedImages.value.filter(item => item.id !== image.id);
};

const handleClearOriginal = () => {
  originalImages.value.forEach(image => {
    URL.revokeObjectURL(image.url);
  });
  processedImages.value.forEach(image => {
    URL.revokeObjectURL(image.url);
  });
  originalImages.value = [];
  processedImages.value = [];
  sourceKey.value = sourceKey.value + 1;
};

const handleClearProcessed = () => {
  processedImages.value.forEach(image => {
    URL.revokeObjectURL(image.url);
  });
  processedImages.value = [];
};
</script>
