// src/components/ProcessNodeScale.vue
<template>
  <div v-if="scaleType === EnumScaleType.RATIO" class="image-scale__controls">
    <div class="image-scale__dimensions">
      <el-radio-group :model-value="scaleRatio" @change="(value: any) => emit('change', value, scaleWidth)">
        <el-radio
          v-for="value in scaleOptions"
          :key="value"
          :value="value"
          class="image-scale__radio"
        >
          {{ value }}x
        </el-radio>
      </el-radio-group>
    </div>
  </div>
  <div v-else class="image-scale__controls">
    <div class="image-scale-width__dimensions">
      <el-input-number
        :model-value="scaleWidth"
        :min="1"
        :max="4096"
        @change="(value: any) => {
          if (value !== null && value >= 1 && value <= 4096) {
            emit('change', scaleRatio, value);
          }
        }"
        style="width: 150px"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { EnumScaleType } from '../types/image';
import './ProcessNodeScale.css';

interface Props {
  scaleType: EnumScaleType;
  scaleRatio: number;
  scaleWidth: number;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  (e: 'change', ratio: number, width: number): void;
}>();

const scaleOptions = [0.25, 0.5, 1, 2, 4];
</script>

// src/components/ProcessNodeScale.tsx
import { InputNumber, Radio } from 'antd';
import React from 'react';
import { EnumScaleType } from '../types/image';
import './ProcessNodeScale.css';

interface ScaleProps {
  scaleType: EnumScaleType;
  scaleRatio: number;
  scaleWidth: number;
  onChange: (ratio: number, width: number) => void;
}

const ProcessNodeScale: React.FC<ScaleProps> = ({ scaleType, scaleRatio, scaleWidth, onChange }) => {
  const scaleOptions = [0.25, 0.5, 1, 2, 4];
  const scaleWidthProps = {
    mode: 'spinner' as const,
    min: 1,
    max: 4096,
    defaultValue: scaleWidth,
    onChange: (e: number | null) => {
      if (e !== null) {
        onChange(scaleRatio, e);
      }
    },
    style: { width: 150 },
  };
  return (
    <>
      {scaleType === EnumScaleType.RATIO ? (
        <div className="image-scale__controls">
          <div className="image-scale__dimensions">
            <Radio.Group value={scaleRatio} onChange={e => onChange(e.target.value, scaleWidth)}>
              {scaleOptions.map(value => (
                <Radio className="image-scale__radio" key={value} value={value}>
                  {value}x
                </Radio>
              ))}
            </Radio.Group>
          </div>
        </div>
      ) : (
        <div className="image-scale__controls">
          <div className="image-scale-width__dimensions">
            <InputNumber {...scaleWidthProps}></InputNumber>
          </div>
        </div>
      )}
    </>
  );
};

export default ProcessNodeScale;
